#!/bin/bash

export PATH=~/.local/bin:$PATH

export SYSTEMD_PAGER= # turn off systemctl auto-paging

export TERM=linux

# editors
export EDITOR=nano
export VISUAL=subl

# gpg
GPG_TTY=$(tty)
export GPG_TTY

# profile
alias reload="\. ~/.bashrc"
alias d-reload="direnv allow && direnv reload"

# rm
alias trash="trash-put"
alias rm="trash-put"
alias rmf="$(type -fP rm)"

# ls
alias ls="ls -h --color=auto"
alias ll="ls -alF"
alias lz="ll -Z"

# sudo
alias sudo="sudo " # sudo with aliases

# python
alias pip-upgrade-all='pip install --upgrade --upgrade-strategy only-if-needed $(pip freeze | cut -d = -f 1) && pip freeze > requirements.txt'
