#!/bin/bash

# CUDA

if [ -d /usr/local/cuda-12.3 ]; then

  export CUDA_DIR=/usr/local/cuda-12.3
  export LD_LIBRARY_PATH=$CUDA_DIR/include:$CUDA_DIR/lib64:$LD_LIBRARY_PATH
  export PATH=$PATH:$CUDA_DIR/bin

fi

# Vulkan

if [ -e /usr/share/vulkan/icd.d/nvidia_icd.x86_64.json ]; then
  export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.x86_64.json
fi

# VA-API

if [ -e /usr/lib64/dri/nvidia_drv_video.so ]; then
  export LIBVA_DRIVERS_PATH=/usr/lib64/dri/nvidia_drv_video.so
fi
