#!/bin/bash

alias docker-compose="docker compose"

throwaway-docker() {

  docker run \
    --rm \
    --gpus all \
    --workdir "$(pwd)" \
    -v "$(pwd)":"$(pwd)" \
    -v /media/throwaway:/media/throwaway \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /usr/bin/docker:/usr/bin/docker \
    "$@"

}

alias throwaway-ubuntu="throwaway-docker -it ubuntu /bin/bash"
alias throwaway-ubuntu-24="throwaway-docker -it ubuntu:24 /bin/bash"
alias throwaway-ubuntu-22="throwaway-docker -it ubuntu:22 /bin/bash"
alias throwaway-ubuntu-20="throwaway-docker -it ubuntu:20 /bin/bash"
alias throwaway-ubuntu-18="throwaway-docker -it ubuntu:18 /bin/bash"

alias throwaway-fedora="throwaway-docker -it fedora /bin/bash"
alias throwaway-fedora-37="throwaway-docker -it fedora:37 /bin/bash"
alias throwaway-fedora-36="throwaway-docker -it fedora:36 /bin/bash"
alias throwaway-fedora-35="throwaway-docker -it fedora:35 /bin/bash"
alias throwaway-fedora-34="throwaway-docker -it fedora:34 /bin/bash"
alias throwaway-fedora-33="throwaway-docker -it fedora:33 /bin/bash"
alias throwaway-fedora-32="throwaway-docker -it fedora:32 /bin/bash"
alias throwaway-fedora-31="throwaway-docker -it fedora:31 /bin/bash"

alias throwaway-amazonlinux="throwaway-docker -it amazonlinux /bin/bash"
alias throwaway-amazonlinux-2023="throwaway-docker -it amazonlinux:2023 /bin/bash"
alias throwaway-amazonlinux-2022="throwaway-docker -it amazonlinux:2022 /bin/bash"
alias throwaway-amazonlinux-2="throwaway-docker -it amazonlinux:2 /bin/bash"
alias throwaway-amazonlinux-1="throwaway-docker -it amazonlinux:1 /bin/bash"

alias throwaway-node="throwaway-docker -it node /bin/bash"
alias throwaway-node-22="throwaway-docker -it node:22 /bin/bash"
alias throwaway-node-20="throwaway-docker -it node:20 /bin/bash"
alias throwaway-node-18="throwaway-docker -it node:18 /bin/bash"
alias throwaway-node-16="throwaway-docker -it node:16 /bin/bash"
alias throwaway-node-14="throwaway-docker -it node:14 /bin/bash"

alias throwaway-python="throwaway-docker -it python /bin/bash"
alias throwaway-python-3.12="throwaway-docker -it python:3.12 /bin/bash"
alias throwaway-python-3.11="throwaway-docker -it python:3.11 /bin/bash"
alias throwaway-python-3.10="throwaway-docker -it python:3.10 /bin/bash"
alias throwaway-python-3.9="throwaway-docker -it python:3.9 /bin/bash"
alias throwaway-python-3.8="throwaway-docker -it python:3.8 /bin/bash"
alias throwaway-python-3.7="throwaway-docker -it python:3.7 /bin/bash"

alias throwaway-ruby="throwaway-docker -it ruby /bin/bash"
alias throwaway-ruby-3.4="throwaway-docker -it ruby:3.4 /bin/bash"
alias throwaway-ruby-3.3="throwaway-docker -it ruby:3.3 /bin/bash"
alias throwaway-ruby-3.2="throwaway-docker -it ruby:3.2 /bin/bash"
alias throwaway-ruby-3.1="throwaway-docker -it ruby:3.1 /bin/bash"
alias throwaway-ruby-2.4="throwaway-docker -it ruby:2.4 /bin/bash"

# user: postgres / password: postgres
alias throwaway-postgres="throwaway-docker -e POSTGRES_USER=postgres POSTGRES_PASSWORD=postgres -p 5432:5432 postgres"
alias throwaway-postgres-17="throwaway-docker -e POSTGRES_USER=postgres POSTGRES_PASSWORD=postgres -p 5432:5432 postgres:17"
alias throwaway-postgres-16="throwaway-docker -e POSTGRES_USER=postgres POSTGRES_PASSWORD=postgres -p 5432:5432 postgres:16"
alias throwaway-postgres-15="throwaway-docker -e POSTGRES_USER=postgres POSTGRES_PASSWORD=postgres -p 5432:5432 postgres:15"
alias throwaway-postgres-14="throwaway-docker -e POSTGRES_USER=postgres POSTGRES_PASSWORD=postgres -p 5432:5432 postgres:14"
alias throwaway-postgres-13="throwaway-docker -e POSTGRES_USER=postgres POSTGRES_PASSWORD=postgres -p 5432:5432 postgres:13"
alias throwaway-postgres-12="throwaway-docker -e POSTGRES_USER=postgres POSTGRES_PASSWORD=postgres -p 5432:5432 postgres:12"
alias throwaway-postgres-11="throwaway-docker -e POSTGRES_USER=postgres POSTGRES_PASSWORD=postgres -p 5432:5432 postgres:11"

# user: root / password: mysql
alias throwaway-mysql="throwaway-docker -e MYSQL_ROOT_PASSWORD=mysql -p 3306:3306 mysql"
alias throwaway-mysql-8="throwaway-docker -e MYSQL_ROOT_PASSWORD=mysql -p 3306:3306 mysql:8"
alias throwaway-mysql-5.7="throwaway-docker -e MYSQL_ROOT_PASSWORD=mysql -p 3306:3306 mysql:5.7"

alias throwaway-redis="throwaway-docker -p 6379:6379 redis"
alias throwaway-redis-7="throwaway-docker -p 6379:6379 redis:7"
alias throwaway-redis-6="throwaway-docker -p 6379:6379 redis:6"

alias throwaway-prefect-3-py-3.11="throwaway-docker -it prefecthq/prefect:3-python3.11 /bin/bash"
alias throwaway-prefect-2-py-3.11="throwaway-docker -it prefecthq/prefect:2-python3.11 /bin/bash"
