#!/bin/bash

# rbenv
# install here: https://github.com/rbenv/rbenv
#   git clone https://github.com/rbenv/rbenv.git ~/.rbenv
#   git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build

eval "$(~/.rbenv/bin/rbenv init - bash)"
