#!/bin/bash

if [ -f ~/.cache/profile.d/pwd ]; then

  __profile_d_new_pwd__=$(cat ~/.cache/profile.d/pwd)

  if [ -d "$__profile_d_new_pwd__" ]; then
    cd "$__profile_d_new_pwd__" || true
  fi

  unset __profile_d_new_pwd__

fi
